"""empty message

Revision ID: 7e48079a66c3
Revises: 
Create Date: 2022-05-09 12:43:30.761666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e48079a66c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commission', sa.Integer(), nullable=True),
    sa.Column('delivery_price', sa.Integer(), nullable=True),
    sa.Column('delivery_duration_from', sa.Integer(), nullable=True),
    sa.Column('delivery_duration_to', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proxy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('ip', sa.String(length=32), nullable=True),
    sa.Column('port', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('kaspi_price', sa.Integer(), nullable=True),
    sa.Column('kaspi_url', sa.String(length=512), nullable=True),
    sa.Column('supplier1_code', sa.String(length=128), nullable=True),
    sa.Column('supplier1_amount', sa.String(length=128), nullable=True),
    sa.Column('supplier1_name', sa.String(length=128), nullable=True),
    sa.Column('supplier1_price', sa.Float(), nullable=True),
    sa.Column('supplier1_margin', sa.Float(), nullable=True),
    sa.Column('supplier1_margin_percent', sa.Float(), nullable=True),
    sa.Column('supplier2_code', sa.String(length=128), nullable=True),
    sa.Column('supplier2_amount', sa.String(length=128), nullable=True),
    sa.Column('supplier2_name', sa.String(length=128), nullable=True),
    sa.Column('supplier2_price', sa.Float(), nullable=True),
    sa.Column('supplier2_margin', sa.Float(), nullable=True),
    sa.Column('supplier2_margin_percent', sa.Float(), nullable=True),
    sa.Column('supplier3_code', sa.String(length=128), nullable=True),
    sa.Column('supplier3_amount', sa.String(length=128), nullable=True),
    sa.Column('supplier3_name', sa.String(length=128), nullable=True),
    sa.Column('supplier3_price', sa.Float(), nullable=True),
    sa.Column('supplier3_margin', sa.Float(), nullable=True),
    sa.Column('supplier3_margin_percent', sa.Float(), nullable=True),
    sa.Column('supplier4_code', sa.String(length=128), nullable=True),
    sa.Column('supplier4_amount', sa.String(length=128), nullable=True),
    sa.Column('supplier4_name', sa.String(length=128), nullable=True),
    sa.Column('supplier4_price', sa.Float(), nullable=True),
    sa.Column('supplier4_margin', sa.Float(), nullable=True),
    sa.Column('supplier4_margin_percent', sa.Float(), nullable=True),
    sa.Column('supplier5_code', sa.String(length=128), nullable=True),
    sa.Column('supplier5_amount', sa.String(length=128), nullable=True),
    sa.Column('supplier5_name', sa.String(length=128), nullable=True),
    sa.Column('supplier5_price', sa.Float(), nullable=True),
    sa.Column('supplier5_margin', sa.Float(), nullable=True),
    sa.Column('supplier5_margin_percent', sa.Float(), nullable=True),
    sa.Column('supplier6_code', sa.String(length=128), nullable=True),
    sa.Column('supplier6_amount', sa.String(length=128), nullable=True),
    sa.Column('supplier6_name', sa.String(length=128), nullable=True),
    sa.Column('supplier6_price', sa.Float(), nullable=True),
    sa.Column('supplier6_margin', sa.Float(), nullable=True),
    sa.Column('supplier6_margin_percent', sa.Float(), nullable=True),
    sa.Column('supplier7_code', sa.String(length=128), nullable=True),
    sa.Column('supplier7_amount', sa.String(length=128), nullable=True),
    sa.Column('supplier7_name', sa.String(length=128), nullable=True),
    sa.Column('supplier7_price', sa.Float(), nullable=True),
    sa.Column('supplier7_margin', sa.Float(), nullable=True),
    sa.Column('supplier7_margin_percent', sa.Float(), nullable=True),
    sa.Column('supplier8_code', sa.String(length=128), nullable=True),
    sa.Column('supplier8_amount', sa.String(length=128), nullable=True),
    sa.Column('supplier8_name', sa.String(length=128), nullable=True),
    sa.Column('supplier8_price', sa.Float(), nullable=True),
    sa.Column('supplier8_margin', sa.Float(), nullable=True),
    sa.Column('supplier8_margin_percent', sa.Float(), nullable=True),
    sa.Column('supplier9_code', sa.String(length=128), nullable=True),
    sa.Column('supplier9_amount', sa.String(length=128), nullable=True),
    sa.Column('supplier9_name', sa.String(length=128), nullable=True),
    sa.Column('supplier9_price', sa.Float(), nullable=True),
    sa.Column('supplier9_margin', sa.Float(), nullable=True),
    sa.Column('supplier9_margin_percent', sa.Float(), nullable=True),
    sa.Column('supplier10_code', sa.String(length=128), nullable=True),
    sa.Column('supplier10_amount', sa.String(length=128), nullable=True),
    sa.Column('supplier10_name', sa.String(length=128), nullable=True),
    sa.Column('supplier10_price', sa.Float(), nullable=True),
    sa.Column('supplier10_margin', sa.Float(), nullable=True),
    sa.Column('supplier10_margin_percent', sa.Float(), nullable=True),
    sa.Column('commission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commission_id'], ['commission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('product')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('proxy')
    op.drop_table('commission')
    # ### end Alembic commands ###
